### PR TITLE
Add support for importing, exporting, and syncing save states

### PR DESCRIPTION
**Pull request by brandosha**

### CODE REVIEW

**Comment by aiq25** [comment]
Hi. How can I use this updated code on my iPhone? Not sure how to make modification since I just saved the Game Play Color from their website.

**Comment by brandosha** [comment]
@aiq25 The modified version is available at https://brandosha.github.io/gameplay/index.html

**Comment by aiq25** [comment]
> 
> 
> @aiq25 The modified version is available at https://brandosha.github.io/gameplay/index.html

Thanks! One more question: When I export a save file, this isn't a .sav format correct? Meaning I cannot use it with other emulators. How can I convert the data?

**Comment by brandosha** [comment]
I'm not entirely sure what the format is. If you try using it with other emulators it would be great if you let me know if it worked or not.

**Comment by aiq25** [comment]
> 
> 
> I'm not entirely sure what the format is. If you try using it with other emulators it would be great if you let me know if it worked or not.

I renamed the exported data to a .sav file and the save works in Visual Boy Advance! Thanks for making these updates to the Game Play Color.

Do you by any chance know how I can retrive a copy of the save from the original Game Play Color?

**Comment by brandosha** [comment]
Issue #100 links to some tutorial videos that someone made.

**Comment by robios** [comment]
@brandosha  I'm trying out your version at https://brandosha.github.io/gameplay/index.html and pull/push of a save data works great but sometimes I have a weird state where the screen not responding any touch, which I didn't see in the previous (original) version. Not sure if this relates to any updates in this version though.

**Comment by brandosha** [comment]
@robios I believe it is related to the snapshot that gets saved when you exit the app. I haven't found the exact cause though.

**Comment by robios** [comment]
@brandosha It happens intermittently while playing a game so I think it may not be related to the snapshot? Could you think of any commits that could affect the user inputs?

**Comment by brandosha** [comment]
@robios Could you open an issue over at [brandosha/gameplaycolor](https://github.com/brandosha/gameplaycolor/issues). Thanks.

**Comment by jbmorley** [comment]
@brandosha I've closed this as it's pretty old now. I'd still love to bring back some of your fantastic changes, and I'm planning to open a separate GitHub issue where we can track that if that works for you. 🙏🏻

**Pull request closed without merging**
