### PR TITLE
Update settings.js

### PR DESCRIPTION
**Pull request by jvhgamer**
Support much faster speeds.

### CODE REVIEW

**Comment by jvhgamer** [comment]
If this isn't a desirable change for the community as a whole, could anyone instruct me on how to deploy the app (with this minor tweak) to an iOS device (hopefully circumventing provisioning profile headaches)? I have access to VS but unsure how to deploy a JS app.

**Comment by nickydraz** [comment]
@jvhgamer I know this is a bit of an old pull request, but if you still want to deploy your own version and haven't figured it out yet, you shouldn't need to worry about provisioning profiles. This runs as a web app, so you just need to build the app and deploy it to a web server, then access it through Safari on your iOS device.

**Comment by imethorsen** [comment]
This doesn't really seem like it's a suitable change for everyday users of the app as it stands.

@jvhgamer Would you be willing to consider preserving the original speeds and adding these as additional ones?

**Comment by imethorsen** [comment]
Closing this pull request. Happy to re-open in the future if there are better approaches to giving users a more practical choice.

**Pull request closed without merging**
